import type { Metadata } from "next";
import { Epilogue } from "next/font/google";
import "./globals.css";
import Header from "@/components/layout/header";

const epilogue = Epilogue({
    subsets: ["latin"],
    weight: ["400"],
    variable: "--font-epilogue",
});

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${epilogue.variable}`}>
                <Header />
                {children}
            </body>
        </html>
    );
}
